services:
  api:
    image: langgenius/dify-api
    restart: always
    env_file:
      - .env
    environment:
      MODE: api
    volumes
      - ./data/api:/app/api/storage
  
  worker:
    image: langgenius/dify-api
    restart: always
    env_file:
      - .env
    environment:
      MODE: worker
    volumes
      - ./data/api:/app/api/storage
  
  web:
    image: langgenius/dify-web
    restart: always
    environment:
      CONSOLE_API_URL: ${CONSOLE_API_URL:-}
      APP_API_URL: ${APP_API_URL:-}
      SENTRY_DSN: ${SENTRY_DSN:-}
  
  sandbox:
    image: langgenius/dify-sandbox
    restart: always
    environment:
      API_KEY: ${SANDBOX_API_KEY:-}
      GIN_MODE: ${SANDBOX_GIN_MODE:-release}
      ENABLE_NETWORK: ${SANDBOX_ENABLE_NETWORK:-true}
      SANDBOX_PORT: ${SANDBOX_PORT:-8194}
    volumes:
      - ./data/sandbox:/dependencies

  weaviate:
    image: semitechnologies/weaviate
    profiles:
      - ''
      - weaviate
    restart: always
    environment:
      PERSISTENCE_DATA_PATH: ${WEAVIATE_PERSISTENCE_DATA_PATH:-/var/lib/weaviate}
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: ${WEAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED:-false}
      AUTHENTICATION_APIKEY_ENABLED: ${WEAVIATE_AUTHENTICATION_APIKEY_ENABLED:-true}
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: ${WEAVIATE_API_KEY:-}
    volumes:
      - ./data/weaviate:/var/lib/weaviate