#!/usr/bin/env bash

# Menggunakan gum untuk memilih tipe berdasarkan folder yang ada
TYPE=$(gum choose $(ls -d */ | cut -f1 -d'/'))

# Memeriksa apakah file docker-compose.yaml ada di folder yang dipilih
if [ -f "$TYPE/docker-compose.yaml" ]; then
    echo "Menjalankan docker-compose untuk $TYPE"
    docker-compose -f "$TYPE/docker-compose.yaml" up -d
else
    echo "File docker-compose.yaml tidak ditemukan di folder $TYPE"
fi

