#!/usr/bin/env bash

TYPE=$(gum choose $(ls -d */ | cut -f1 -d'/'))

if [ -f "$TYPE/docker-compose.yaml" ]; then
    echo "Running service $TYPE"
    docker-compose -f "$TYPE/docker-compose.yaml" up -d
else
    echo "No docker-compose.yaml file at $TYPE"
fi

