services:
  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/site:/srv
      - ./data/data:/data
      - ./data/config:/config
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true
