services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    env_file:
      - .env
    volumes:
      - ./data/n8n:/home/node/.n8n
    networks:
      - cloudflared
      - n8n-network

networks:
  cloudflared:
    external: true
  n8n-network:
    driver: bridge
